"""change face_embedding type to jsonb

Revision ID: decdaf31c866
Revises: 4feebbf5c234
Create Date: 2026-06-30 18:12:09.208381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'decdaf31c866'
down_revision: Union[str, Sequence[str], None] = '4feebbf5c234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_faces', 'face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='face_embedding::text::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_faces', 'face_embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=False)
    # ### end Alembic commands ###
